version: "3"

services:
  frontend:
    build: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 3000:3000
  backend:
    image: "mattrayner/lamp:latest-1604-php5" # PHP 5
    volumes:
      - ${PWD}/api:/app
      - ${PWD}/app/dist:/app/dist
      - ${PWD}/db:/var/lib/mysql
    ports:
      - 3001:80
