version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
  backend:
    image: 'mattrayner/lamp:latest-1604-php5' # PHP 5
    volumes:
      - ${PWD}/app:/app
      - ${PWD}/db:/var/lib/mysql
    ports:
      - 3001:80
